#ifndef SE_GAMEPLAY_PLAYER_POSSIBLE_ACTIONS_H
#define SE_GAMEPLAY_PLAYER_POSSIBLE_ACTIONS_H

namespace SE
{
	namespace Gameplay
	{
		enum class PlayerMovementActions
		{
			PLAYER_MOVEMENT_UP,
			PLAYER_MOVEMENT_UP_LEFT,
			PLAYER_MOVEMENT_LEFT,
			PLAYER_MOVEMENT_DOWN_LEFT,
			PLAYER_MOVEMENT_DOWN,
			PLAYER_MOVEMENT_DOWN_RIGHT,
			PLAYER_MOVEMENT_RIGHT,
			PLAYER_MOVEMENT_UP_RIGHT,
			PLAYER_MOVEMENT_STAY_STILL,
			PLAYER_MOVEMENT_ENUM_SIZE /*<ALWAYS LAST!*/
		};

		enum class PlayerAttackActions
		{
			PLAYER_ATTACK_SHOOT,
			PLAYER_ATTACK_NONE,
			PLAYER_ATTACK_ENUM_SIZE /*< ALWAYS LAST!*/
		};
	}
}



#endif